"use client";

import esNames from "@/data/names.es.json";
import { createContext, use, useEffect, useMemo, useState } from "react";
import { languages } from "./messages";
import { createTranslator, detectLocale, locales, parseRichText } from "./translate";

// In-game item names per language, generated by scripts/build-catalog.mjs.
// Missing entries (e.g. Primes newer than the build) fall back to English.
const ITEM_NAMES = { es: esNames };

const SETTINGS_KEY = "primeInventoryLanguage";

const loadSettings = () => {
  const detected = { locale: detectLocale(navigator.languages ?? [navigator.language]), itemNames: "en" };
  try {
    const saved = JSON.parse(localStorage.getItem(SETTINGS_KEY)) ?? {};
    return {
      locale: locales.includes(saved.locale) ? saved.locale : detected.locale,
      itemNames: saved.itemNames === "localized" ? "localized" : "en",
    };
  } catch {
    return detected;
  }
};

const I18nContext = createContext(undefined);

export function I18nProvider({ children }) {
  const [settings, setSettings] = useState(loadSettings);
  const { locale, itemNames } = settings;

  useEffect(() => {
    document.documentElement.lang = locale;
    try {
      localStorage.setItem(SETTINGS_KEY, JSON.stringify(settings));
    } catch {
      // The language is still detected from the browser next time.
    }
  }, [locale, settings]);

  const value = useMemo(() => {
    const t = createTranslator(locale);
    const numberFormat = new Intl.NumberFormat(locale);
    const names = itemNames === "localized" ? ITEM_NAMES[locale] : undefined;

    const setName = (set) => names?.sets[set.uniqueName] ?? set.name;
    const partName = (part) => names?.parts[part.uniqueName] ?? part.name;

    return {
      locale,
      itemNames,
      languages,
      setLocale: (next) => setSettings((current) => ({ ...current, locale: next })),
      setItemNames: (next) => setSettings((current) => ({ ...current, itemNames: next })),
      t,
      formatNumber: (value) => numberFormat.format(value),
      setName,
      partName,
      // "Ash Prime Chassis" or, with Spanish item names, "Chasis de Ash Prime".
      fullPartName: (set, part) =>
        names && locale === "es" ? `${partName(part)} de ${setName(set)}` : `${setName(set)} ${partName(part)}`,
      /** t() for messages with <b>/<em> emphasis, rendered with the given elements. */
      rich: (key, vars, renderers) =>
        parseRichText(t(key, vars)).map((part, index) =>
          typeof part === "string" ? part : (renderers[part.tag]?.(part.text, index) ?? part.text)
        ),
    };
  }, [locale, itemNames]);

  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export const useI18n = () => use(I18nContext);
